# Generated by Django 2.2.19 on 2021-04-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
