# Generated by Django 2.2.19 on 2021-04-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
