export const products = [
    {
      categoryId:1,
      id:1,
      name: "Acer Aspire 5 Slim Laptop, 15.6 inches Full HD IPS Display, AMD Ryzen 3 3200U, Vega 3 Graphics, 4GB DDR4, 128GB SSD, Backlit Keyboard, Windows 10 in S Mode, A515-43-R19L, Silver",
      price: 449,
      description: "The multiple available colors of this fashionable laptop hides a choice of powerful processors and graphics which will help users get the most of the screen its large screen-to-body ratio. As you’d expect from a laptop of this caliber it also includes fast Wi-Fi and plenty of storage and memory.",
      rating: 4.6,
      likes: 90,
      image: 'https://images-na.ssl-images-amazon.com/images/I/71vvXGmdKWL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Acer-i5-8265U-Keyboard-Fingerprint-A515-54-51DJ/dp/B07RF2123Z'
    },
    {
      categoryId:2,
      id:2,
      name: "Roku Premiere | HD/4K/HDR Streaming Media Player, Simple Remote and Premium HDMI Cable",
      price: 34.44,
      description: "4K & HDR streaming made easy   Incredible picture at an incredible value. Roku Premiere is the simple way to start streaming in HD, 4K, and HDR. Easily find and enjoy movies in brilliant 4K picture with the 4K Spotlight channel. Setup is simple—just plug it into your TV with the included Premium High Speed HDMI Cable and connect to the internet.   Stream what you love, including live TV, news, sports, hit movies, popular shows, and more. Plus, with access to hundreds of free channels, there’s plenty to enjoy without spending extra. TV Compatibility",
      rating: 4.7,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/81wHpn6wPLL._AC_SY450_.jpg',
      address: 'https://www.amazon.com/Roku-Premiere-HDR-Streaming-Player-Premium/dp/B07HDBZN7Q'
    },
    {
      categoryId:1,
      id:3,
      name: "HP VH240a 23.8-Inch Full HD 1080p IPS LED Monitor with Built-In Speakers and VESA Mounting, Rotating Portrait & Landscape, Tilt, and HDMI & VGA Ports (1KL30AA) - Black",
      price: 163,
      description: "Get the best productivity from home or at the office with the virtually borderless HP VH240a 23.8-Inch display featuring an ergonomic stand, built-in speakers and an ultra-slim design at a competitively low price point. Great for projects requiring portrait and landscape mode screen rotation, the VH240a also includes a 178° positional viewing angle for the best quality no matter where you sit. You can also mount the display on a wall or arm bracket with a 100m VESA mounting pattern located on the back of the monitor arm. Connect your Windows, Mac, or any laptop featuring an HDMI port with an included HDMI cord. The video card of the connected PC must be capable of supporting 1920 x 1080 at 60 Hz and include 1 HDMI or 1 VGA output to drive the monitor at the preferred mode.",
      rating: 4.7,
      image: 'https://images-na.ssl-images-amazon.com/images/I/71trhuzbhML._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/HP-23-8-inch-Adjustment-Speakers-VH240a/dp/B072M34RQC'
    },
    {
      categoryId:1,
      id:4,
      name: "AMD Ryzen 5 3600 6-Core, 12-Thread Unlocked Desktop Processor with Wraith Stealth Cooler",
      price: 199.99,
      description: "AMD CPU 100 100000031box Ryzen 5 3600 6C 12T 4200MHz 36MB 65W AM4 Wraith Stealth.",
      rating: 4.9,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/71WPGXQLcLL._AC_SL1384_.jpg',
      address: 'https://www.amazon.com/AMD-Ryzen-3600-12-Thread-Processor/dp/B07STGGQ18'
    },
    {
      categoryId:1,
      id:5,
      name: "BOOX Note Air 10.3 ePaper, Android 10, Front Light, G-Sensor, Digital Paper, E Ink Notepad",
      price: 479.99,
      description: "Like A Tablet, Unlike Any Tablet. Thin, large capable, with front light. Watch how Note Air can perfectly fit in your digital lifestyle.The body of 5.8mm thickness allows you to grasp Note Air firmly and effortlessly. With the adjustable front light, you can get the most comfortable view on the 227dpi HD screen in any light.",
      rating: 4.1,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/618wPmm0hBL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/BOOX-Android-G-Sensor-Digital-Notepad/dp/B08H83GCBT/ref=sr_1_2?dchild=1&fst=as%3Aoff&pd_rd_r=2f5e977e-9cee-41bf-ad94-8a284b2b0880&pd_rd_w=LF3jp&pd_rd_wg=TFnJ2&pf_rd_p=83ab1c34-7657-4d09-b72d-0a3e4b634b1d&pf_rd_r=4F75Y22P76YA3BXE401P&qid=1602294815&rnid=16225007011&s=computers-intl-ship&sr=1-2'
    },
    {
      categoryId:1,
      id:6,
      name: "Fingbox Home Network Monitoring, Security & Control - Stop Intruders & Hackers, Control Screen Time, Get Internet Performance Reports & Automate Your Connected Home. Now on Google Assistant.",
      price: 99,
      description: "Fingbox is a puck-sized device which plugs into your network at home and opens a new realm of control and knowledge about every device that connects to your home network, wired or wireless. Fingbox allows the user to control device time on the Internet, what the user can look at, perform troubleshooting to understand why the Internet is lagging, and protect from cyber hacking.",
      rating: 4.2,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/61v8erz5WgL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Fing-Fingbbox/dp/B07JMFHNW7/ref=sr_1_8?dchild=1&fst=as%3Aoff&pd_rd_r=2f5e977e-9cee-41bf-ad94-8a284b2b0880&pd_rd_w=LF3jp&pd_rd_wg=TFnJ2&pf_rd_p=83ab1c34-7657-4d09-b72d-0a3e4b634b1d&pf_rd_r=4F75Y22P76YA3BXE401P&qid=1602294815&rnid=16225007011&s=computers-intl-ship&sr=1-8'
    },
    {
      categoryId:1,
      id:7,
      name: "Libre Computer Board AML-S905X-CC (Le Potato) 2GB 64-bit Mini Computer for 4K Media",
      price: 35,
      description: "HIGH PERFORMANCE DESIGN: Quad 64-bit 1.5GHz ARM Cortex-A53 Processors, 4K Ultra HD ARM Mali-450 750MHz GPU, 2GB of High Bandwidth DDR3, 4K 60FPS High Dynamic Range Display Engine for H.265 HEVC, H.264 AVC, VP9 Hardware Decoding and 1080P 60FPS H.264 Harware Encoding, Up to 50% faster than Raspberry Pi 3.",
      rating: 4.1,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/91iQjFVDjcL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Libre-Computer-AML-S905X-CC-Potato-64-bit/dp/B074P6BNGZ/ref=sr_1_15?dchild=1&fst=as%3Aoff&pd_rd_r=2f5e977e-9cee-41bf-ad94-8a284b2b0880&pd_rd_w=LF3jp&pd_rd_wg=TFnJ2&pf_rd_p=83ab1c34-7657-4d09-b72d-0a3e4b634b1d&pf_rd_r=4F75Y22P76YA3BXE401P&qid=1602294815&rnid=16225007011&s=computers-intl-ship&sr=1-15'
    },
    {
      categoryId:1,
      id:8,
      name: "HP EliteBook 840 G6 14 Notebook - Core i7 i7-8565U - 16 GB RAM - 512 GB SSD - Windows 10 Pro - in-Plane Switching (IPS) Technology - English Keyboard - Intel Optane Memory Ready - 17.25 Hour Bat",
      price: 1544.45,
      description: "HP EB840G6 i7-8565U 14 16GB/512 PC Intel i7-8565U, 14. 0 FHD AG LED UWVA, UMA, Webcam, 16GB DDR4, 512GB SSD, abet, 3C Batt, FPR, W10 Pro64, 3yr Warty U. S. - English localization",
      rating: 4,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/811p1jxp2pL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/HP-EliteBook-840-Notebook-Plane/dp/B07VBHBRM1/ref=sr_1_16?dchild=1&fst=as%3Aoff&pd_rd_r=2f5e977e-9cee-41bf-ad94-8a284b2b0880&pd_rd_w=LF3jp&pd_rd_wg=TFnJ2&pf_rd_p=83ab1c34-7657-4d09-b72d-0a3e4b634b1d&pf_rd_r=4F75Y22P76YA3BXE401P&qid=1602294815&rnid=16225007011&s=computers-intl-ship&sr=1-16'
    },
    {
      categoryId:1,
      id:9,
      name: "Smart Buy Z2 G4 S I7-9700 512GB 16GB NVD QDRO P1000 W10P6",
      price: 1310.29,
      description: "SMART BUY Z2 G4 S I7-9700 512GB 16GB NVD QDRO P1000 W10P6",
      rating: 0,
      likes: 0,
      image: 'https://images-na.ssl-images-amazon.com/images/I/41MMeS%2BqKLL._AC_.jpg',
      address: 'https://www.amazon.com/Smart-I7-9700-512GB-P1000-W10P6/dp/B07YDYMGRD/ref=sr_1_29?dchild=1&fst=as%3Aoff&pd_rd_r=2f5e977e-9cee-41bf-ad94-8a284b2b0880&pd_rd_w=LF3jp&pd_rd_wg=TFnJ2&pf_rd_p=83ab1c34-7657-4d09-b72d-0a3e4b634b1d&pf_rd_r=4F75Y22P76YA3BXE401P&qid=1614062286&rnid=16225007011&s=computers-intl-ship&sr=1-29'
    },
    {
      categoryId:5,
      id:10,
      name: "5.1 inch Multi-Function Retro Game Console Handheld Game Console 9600 Games Support Emulator Games can be archived with Rechargeable Lithium Battery (Black)",
      price: 69.8,
      description: "5.1-inch high-definition LCD screen, arcade system, built-in games, although it is not the best game console, but it will definitely bring you happiness, let you recall the nostalgic classic time.",
      rating: 4.1,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/71XOOkvfHuL._AC_SL1230_.jpg',
      address: 'https://www.amazon.com/Multi-Function-Handheld-Emulator-archived-Rechargeable/dp/B087YW4S21/ref=sr_1_47?dchild=1&fst=as%3Aoff&pd_rd_r=2f5e977e-9cee-41bf-ad94-8a284b2b0880&pd_rd_w=LF3jp&pd_rd_wg=TFnJ2&pf_rd_p=83ab1c34-7657-4d09-b72d-0a3e4b634b1d&pf_rd_r=4F75Y22P76YA3BXE401P&qid=1614062286&rnid=16225007011&s=computers-intl-ship&sr=1-47'
    },
    {
      categoryId:2,
      id:11,
      name:"Smart WiFi Light Bulb, LED RGBCW Color Changing, Compatible with Alexa and Google Home Assistant, No Hub Required, A19 E26 Multicolor LUMIMAN 2 Pack",
      price: 18.99,
      description:"VOICE CONTROL - LUMIMAN Smart bulb no hub compatible with Alexa Echo (via PlusMinus skill), Echo dot and Google Home Assistant, control the wifi bulb via your voice, No hub required. (e.g. ‘Alexa, set the bedroom to purple’)",
      rating:4.4,
      likes: 10,
      image: 'https://images-na.ssl-images-amazon.com/images/I/61axAPdYt3L._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Changing-Compatible-Assistant-Multicolor-LUMIMAN/dp/B07DLSNNDS/ref=lp_21217035011_1_1?s=specialty-aps'
    },
    {
      categoryId:5,
      id:12,
      name:"Marvel's Spider-Man: Miles Morales Ultimate Launch Edition – PlayStation 5",
      price: 69,
      description:"Miles Morales discovers explosive powers that set him apart from his mentor, Peter Parker. Master his unique, bio-electric venom blast attacks and covert camouflage power alongside spectacular web-slinging acrobatics, gadgets and skills.",
      rating:4.517,
      likes: 1000,
      image: 'https://images-na.ssl-images-amazon.com/images/I/71bqboqDUiL._SL1361_.jpg',
      address: 'https://www.amazon.com/Marvels-Spider-Man-Morales-Ultimate-Launch-PlayStation/dp/B08FC66ZV4/ref=sr_1_4?dchild=1&fst=as%3Aoff&pf_rd_i=16225016011&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=03b28c2c-71e9-4947-aa06-f8b5dc8bf880&pf_rd_r=C8ZRG3NGP702YHAH3WXQ&pf_rd_s=merchandised-search-3&pf_rd_t=101&qid=1614671485&refinements=p_89%3APlaystation&rnid=2528832011&s=videogames-intl-ship&sr=1-4'
    },
    {
      categoryId:5,
      id:13,
      name: "Super Mario 3D World + Bowser's Fury - Nintendo Switch",
      price: 59.99,
      description: "Super Mario 3D World can be played locally* on the same system, via local wireless, or online** with up to three other players for cooperation…and some friendly competition",
      rating: 4.9,
      likes: 1699,
      image: 'https://images-na.ssl-images-amazon.com/images/I/81TK5d%2BI%2ByL._SL1500_.jpg',
      address: 'https://www.amazon.com/Super-Mario-3D-World-Bowsers-Fury/dp/B08H9M7LDY/ref=lp_16225016011_1_3'
    },
    {
      categoryId:5,
      id:14,
      name: "Nintendo Switch - Mario Red & Blue Edition - Switch",
      price: 369.8,
      description: "This Nintendo Switch system takes inspiration from Mario, with a bold red design on the Nintendo Switch Console, Joy-Con controllers, and the Nintendo Switch dock.",
      rating: 4.9,
      likes: 65625,
      image: 'https://images-na.ssl-images-amazon.com/images/I/71K3XD9oosL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Nintendo-Switch-Mario-Red-Blue/dp/B08M8YQMH4/ref=lp_16225016011_1_5'
    },
    {
      categoryId:5,
      id:15,
      name: "Oculus Quest 2 — Advanced All-In-One Virtual Reality Headset — 64 GB",
      price: 299,
      description: "Oculus Quest 2 is our most advanced all-in-one VR system yet. Every detail has been engineered to make virtual worlds adapt to your movements, letting you explore awe-inspiring games and experiences with unparalleled freedom. No PC or console required. Get the most out of each moment with blazing-fast performance and next-generation graphics. Stay focused with a stunning display that features 50% more pixels than the original Quest. Or take a break from the action and grab front-row seats to live concerts, exclusive events and more. The redesigned Touch controllers feature improved ergonomics and intuitive controls that transport your gestures, motions and actions directly into VR. You can even connect your VR headset to a gaming-compatible computer with an Oculus Link cable to access hundreds of PC VR games and experiences. Quest 2 also lets you bring your friends into the action. With live casting, you can share your VR experience with people around you. Or meet up with friends in virtual worlds to battle in multiplayer competitions or just spend some time together. With Oculus Quest 2, there’s no end in sight to what you can play, create and discover in virtual reality.",
      rating: 4.8,
      likes: 27208,
      image: 'https://images-na.ssl-images-amazon.com/images/I/615YaAiA-ML._SL1500_.jpg',
      address: 'https://www.amazon.com/Oculus-Quest-Advanced-All-One-2/dp/B08F7PTF53/ref=lp_16225016011_1_1'
    },
    {
      categoryId:3,
      id:16,
      name: "Art Supplies 35-Pieces Sketching and Drawing Pencils Set,Include Graphite Pencils Charcoal Pencils,Eraser,Sharpener, Holiday Gift for Adults &Teens",
      price: 18.99,
      description: "Portable design-35in1 design. When the zipper is closed, it can effectively protect the safety of the internal painting tools. When closed,The Drawing Pencils Set does not take up space and can be put in a suitcase or backpack. Our Drawing Pencils Set allows you to create beautiful works on the way of travel, business trip or vacation. No matter where you go, you can leave the most perfect painting.",
      rating: 0,
      likes: 0,
      image: 'https://images-na.ssl-images-amazon.com/images/I/81CNMJwsUCL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Supplies-35-Pieces-Sketching-Graphite-Sharpener/dp/B08RYMWXS3/ref=sr_1_2_sspa?dchild=1&pf_rd_i=4954955011&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=be595753-2725-49f0-94e9-34baf0bd1f32&pf_rd_r=EK7KY5E84G15CS20Y7F6&pf_rd_s=merchandised-search-2&pf_rd_t=101&qid=1614671962&s=arts-crafts-intl-ship&sr=1-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFGVjJBVjdaSktQTVomZW5jcnlwdGVkSWQ9QTEwMzU4NDEzSDAzVTgyTEYwSkc5JmVuY3J5cHRlZEFkSWQ9QTA3MjUyMjMyUjk5M1ZWU0swRDlPJndpZGdldE5hbWU9c3BfYXRmX2Jyb3dzZSZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU='
    },
    {
      categoryId:3,
      id:17,
      name: "YRYM HT Clear Vinyl Transfer Paper Tape Roll-12 x 50 FT w/Alignment Grid Application Tape for Silhouette Cameo, Cricut Adhesive Vinyl for Decals,Signs, Windows, Stickers",
      price: 16.99,
      description: "Premium 12x50 Ft Transfer Tape for Vinyl-It goes a long way to complete your project and much more. Easy to Use & Transfer Vinyl Transfer Tape was designed to work with a wide variety of Adhesive vinyl including Indoor and Outdoor. It can work with Provo Craft Cricut vinyl, silhouette cameo or portrait vinyl, puzzles, and much more. The vinyl transfer tape is perfect for most self adhesive vinyl and you won't find better all around transfer tape.",
      rating: 4.7,
      likes: 25729,
      image: 'https://images-na.ssl-images-amazon.com/images/I/71CYutTwMsL._SL1500_.jpg',
      address: 'https://www.amazon.com/YRYM-HT-Alignment-Application-Silhouette/dp/B07KPB38LK/ref=lp_4954955011_1_5'
    },
    {
      categoryId:3,
      id:18,
      name: "BOSOBO Paint Brushes Set, 2 Pack 20 Pcs Round Pointed Tip Paintbrushes Nylon Hair Artist Acrylic Paint Brushes for Acrylic Oil Watercolor, Face Nail Art, Miniature Detailing & Rock Painting, Blue",
      price: 6.99,
      description: "",
      rating: 4.7,
      likes: 22050,
      image: 'https://images-na.ssl-images-amazon.com/images/I/81ON4-sLO0L._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/BOSOBO-Paintbrushes-Watercolor-Miniature-Detailing/dp/B07GH7WGC3/ref=lp_4954955011_1_4'
    },
    {
      categoryId:3,
      id:19,
      name: "Charm Bracelet Making Kit, 96pcs Girls Bracelet Making Kit with Beads, Bracelet, Necklace and Gift Box for Kids and Adults",
      price: 18.99,
      description: "PACKAGE INCLUDE - This bracelet making kit for teens contains 30pcs mental spacer beads, 24pcs rainbow beads, 23pcs beads with dangle, 6pcs rhinestone beads, 5pcs snake bracelet, 3pcs waxed necklace cord, 2pcs bead chain, 2pcs silver necklace extenders and a gift box to store the kids bracelet making kit for girls",
      rating: 5,
      likes: 2,
      image: 'https://m.media-amazon.com/images/S/aplus-media/sc/f183cfbc-eec6-43ad-8f01-fd43578ec1fc.__CR0,0,970,600_PT0_SX970_V1___.jpg',
      address: 'https://www.amazon.com/Charm-Bracelet-Making-Necklace-Adults/dp/B08QQZLH5Q/ref=sr_1_1_sspa?dchild=1&pf_rd_i=4954955011&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=be595753-2725-49f0-94e9-34baf0bd1f32&pf_rd_r=R7TSKPFG5M48BYWBM72M&pf_rd_s=merchandised-search-2&pf_rd_t=101&qid=1614672307&s=arts-crafts-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExVUtLSEtDU05PQlcmZW5jcnlwdGVkSWQ9QTAyODA2NzIzWTY1R0ZRUTFJQkkmZW5jcnlwdGVkQWRJZD1BMDUzMjIzNTI0QkIwUzNRQTZEQlMmd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3NlJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=='
    },
    {
      categoryId:3,
      id: 20,
      name: "3 Pack PTFE Teflon Sheet for Heat Press Transfer Sheet Non Stick 16 x 20 Heat Transfer Paper Reusable Heat Resistant Craft Mat",
      price: 6.99,
      description: "Waterproof & Washable-Our 3 pack Teflon Sheet for Heat Press Reusable is easily wipe off messy materials like wipe glue, wax or clay ",
      rating: 4.7,
      likes: 21017,
      image:'https://images-na.ssl-images-amazon.com/images/I/71syLvVXbCL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Teflon-Sheet-Transfer-Reusable-Resistant/dp/B07H55M1ZR/ref=sr_1_9?dchild=1&pf_rd_i=4954955011&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=be595753-2725-49f0-94e9-34baf0bd1f32&pf_rd_r=R7TSKPFG5M48BYWBM72M&pf_rd_s=merchandised-search-2&pf_rd_t=101&qid=1614672460&s=arts-crafts-intl-ship&sr=1-9'
    },
    {
      categoryId:4,
      id: 21,
      name: "Maybelline Lash Sensational Washable Mascara, Blackest Black, 0.32 fl; Oz; (Packaging May Vary)",
      price: 6.49,
      description: "Get a sensational full-fan effect with Maybelline New York’s fan favorite Lash Sensational Washable Mascara! Lashes grow in more than one layer. This volumizing mascara can unfold layer upon layer of lashes thanks to its exclusive brush with ten layers of bristle. Maybelline’s best lengthening mascara lengthens and volumizes lashes from root to tip. The buildable liquid ink waterproof formula coats from all sides without clumping. The fresh liquid formula is ophthalmologist tested and safe for contact lens wearers. Complete your eye makeup look with another Maybelline’s fan favorite Master Precise Liquid Eyeliner and your favorite City Mini Eyeshadow Palette.",
      rating: 4.5,
      likes: 51154,
      image:'https://images-na.ssl-images-amazon.com/images/I/51tvj%2BDeJML._SL1000_.jpg',
      address: 'https://www.amazon.com/Maybelline-Sensational-Washable-Mascara-Blackest/dp/B00PFCT2R0/ref=sr_1_6?dchild=1&qid=1614672651&s=beauty-intl-ship&sr=1-6'
    },{
      categoryId:4,
      id: 22,
      name: "Revlon Age Defying with DNA Advantage Makeup, Soft Beige",
      price: 11.49,
      description: "ULTIMATE ANTI-AGING FOUNDATION: Our age defying firming and lifting makeup with age-preventive Tri-Shield Technology, works as a moisturizer, serum, and primer all in one",
      rating: 4.6,
      likes: 2349,
      image:'https://images-na.ssl-images-amazon.com/images/I/51erxZ2dvBL._SL1000_.jpg',
      address: 'https://www.amazon.com/Revlon-Defying-Firming-Lifting-Makeup/dp/B00I52QP9A/ref=sr_1_14_sspa?dchild=1&qid=1614672743&s=beauty-intl-ship&sr=1-14-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExOTgyOTJJMzkyOTUmZW5jcnlwdGVkSWQ9QTA4NjEwNTIzUDdTNkhSQzJKMFZPJmVuY3J5cHRlZEFkSWQ9QTAxODM3MDMyQzBINDM4WldFMlEzJndpZGdldE5hbWU9c3BfbXRmX2Jyb3dzZSZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU='
    },
    {
      categoryId:4,
      id: 23,
      name: "The Ordinary Hyaluronic Acid 2% + B5 30ml",
      price: 12.66,
      description: "Hyaluronic Acid (HA) can attract up to 1,000 times its weight in water. The molecular size of HA determines its depth of delivery in the skin. This formulation combines low-, medium- and high-molecular weight HA, as well as a next-generation HA crosspolymer at a combined concentration of 2% for multi-depth hydration in a water-based formula. This system is supported with the addition of Vitamin B5 which also enhances surface hydration. This product has NO safety seal.",
      rating: 4.6,
      likes: 11724,
      image:'https://images-na.ssl-images-amazon.com/images/I/71gz%2B5W%2BIvL._SL1500_.jpg',
      address: 'https://www.amazon.com/Ordinary-Hyaluronic-Acid-2-30ml/dp/B01MYEZPC8/ref=sr_1_20?dchild=1&qid=1614672743&s=beauty-intl-ship&sr=1-20'
    },{
      categoryId:4,
      id: 24,
      name: "Mentholatum Natural Ice Lip Balm Original SPF 15 1 Each ( Pack of 12)",
      price: 12.73,
      description: "For over 25 years, Natural Ice has been the go-to lip balm for everyday family use, helping to protect lips from harsh environmental conditions. Natural Ice lip balm has a natural cooling sensation that tells you it’s working. Available in both original and cherry flavors, its smooth glide-on formula with SPF 15 gives long-lasting protection and helps heal dry, chapped lips. Natural Ice Sport is specially designed for extreme weather conditions and provides year round protection from the effects of sun, wind, cold and heat. It goes on smooth while providing broad spectrum UVA and UVB SPF 30 protection.",
      rating: 4.9,
      likes: 2638,
      image:'https://images-na.ssl-images-amazon.com/images/I/715mE-f0nWL._AC_SL1500_.jpg',
      address: 'https://www.amazon.com/Mentholatum-Natural-Ice-Balm-Original/dp/B000052YE5/ref=sr_1_1_sspa?dchild=1&qid=1614672947&rnid=3777891&s=beauty-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExVjRHNVVERkVUQlM0JmVuY3J5cHRlZElkPUEwMzM2NDk1N1haQUhXRzlINkEwJmVuY3J5cHRlZEFkSWQ9QTA5NzA5NjQyU05ONU40MFU1WUE2JndpZGdldE5hbWU9c3BfYXRmX2Jyb3dzZSZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU='
    },{
      categoryId:4,
      id: 25,
      name: "TruSkin Vitamin C Serum for Face with Hyaluronic Acid, Vitamin E, Witch Hazel, 1 fl oz",
      price: 19.99,
      description: "ANTIOXIDANT FACE SERUM - Vitamin C blends with Botanical Hyaluronic Acid, Vitamin E, Witch Hazel, and Jojoba Oil to promote your skin's response to signs of aging like brightness, wrinkles, & dark spots",
      rating: 4.3,
      likes: 62795,
      image:'https://images-na.ssl-images-amazon.com/images/I/516yN4iPdQL._SL1250_.jpg',
      address: 'https://www.amazon.com/TruSkin-Naturals-Vitamin-Topical-Hyaluronic/dp/B01M4MCUAF/ref=sr_1_5?dchild=1&qid=1614673046&rnid=3777891&s=beauty-intl-ship&sr=1-5'
    },
    {
      categoryId:2,
      id: 26,
      name: "August Smart Lock Pro (3rd Gen) + Connect Hub - Zwave, HomeKit & Alexa Compatible - Silver",
      price: 129.25,
      description: "Control and monitor your door from anywhere. Lock and unlock your door, control, keyless access and keep track of who comes and goes, all from your phone. Alexa can also provide notifications when your battery is running low so you can proactively replace them. Set up smart reorders through dash replenishment to make sure you always have replacement batteries when you need them.",
      rating: 4.4,
      likes: 9669,
      image:'https://images-na.ssl-images-amazon.com/images/I/519AkRwE2pL._AC_SL1000_.jpg',
      address: 'https://www.amazon.com/August-Smart-Lock-Connect-technology/dp/B0752V8D8D/ref=lp_21216824011_1_6?s=specialty-aps'
    },
    {
      categoryId:2,
      id: 27,
      name: "Arlo - Wireless Home Security Camera System | Night vision, Indoor/Outdoor, HD Video, Wall Mount | Includes Cloud Storage & Required Base Station | 1-Camera System (VMS3130)",
      price: 139.00,
      description: "The Arlo camera is a 100 Percent Wire-Free, completely wireless, HD smart home security camera – so you can get exactly the shot you need – inside or out. The Arlo camera is weather-resistant and includes motion detection, night vision, and apps. It can capture clips and send you alerts whether you’re at home or away for round-the-clock peace of mind.",
      rating: 3.7,
      likes: 4765,
      image:'https://m.media-amazon.com/images/S/aplus-media/vc/a611f52c-e6ee-44c9-a6c3-90d44ea0fc8c._SR285,285_.jpg',
      address: 'https://www.amazon.com/Arlo-Wireless-Security-Detection-Included/dp/B00QH0Q8J4/ref=lp_21217033011_1_4?s=specialty-aps'
    },
    {
      categoryId:2,
      id: 28,
      name: "WYZE Cam Outdoor Starter Bundle (Includes Base Station and 1 Camera), 1080p HD Indoor/Outdoor Wire-Free Smart Home Camera with Night Vision, 2-Way Audio, Works with Alexa & Google Assistant, White",
      price: 59.99,
      description: "Our customers have inspired us over the last two years with videos of meteors racing across the sky, sunsets over mountain ranges we thought only existed in movies, and visits from mother nature in the form of wildlife and spectacular lightning storms. They’ve stretched the limits of our indoor camera with use cases we never anticipated and conditions we thought impossible. They made makeshift outdoor housings out of milk jugs, 3D printings, and bird houses.",
      rating: 4.7,
      likes: 3173,
      image:'https://images-na.ssl-images-amazon.com/images/I/41SyuiCk7JL._AC_SL1001_.jpg',
      address: 'https://www.amazon.com/dp/B08FFJWQY1/ref=s9_acsd_al_bw_c2_x_0_t?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=4G1TEEVSQQ82BW0R84Z0&pf_rd_t=101&pf_rd_p=07d3dcde-01c7-42e2-b4bf-80eb5a972100&pf_rd_i=21217033011'
    }
    
  ]